Entering function f
*  with variables {'x': 2, 'y': 4, 'z': 6}
*  on line 3 of /home/fred/Projects/tracing_test/test.py
*  from line 10 of /home/fred/Projects/tracing_test/test.py
Executing line 4 --> 	if (type(x).__name__ != 'int' or type(y).__name__ != 'int' or type(z).__name__ != 'int'):
*  with variables {'x': 2, 'y': 4, 'z': 6}
*  of /home/fred/Projects/tracing_test/test.py
Executing line 7 --> 	print(x + y + z)
*  with variables {'x': 2, 'y': 4, 'z': 6}
*  of /home/fred/Projects/tracing_test/test.py
12
Entering function f
*  with variables {'x': True, 'y': 1, 'z': 6}
*  on line 3 of /home/fred/Projects/tracing_test/test.py
*  from line 10 of /home/fred/Projects/tracing_test/test.py
Executing line 4 --> 	if (type(x).__name__ != 'int' or type(y).__name__ != 'int' or type(z).__name__ != 'int'):
*  with variables {'x': True, 'y': 1, 'z': 6}
*  of /home/fred/Projects/tracing_test/test.py
Executing line 5 --> 		raise ValueError('Invalid parameters !')
*  with variables {'x': True, 'y': 1, 'z': 6}
*  of /home/fred/Projects/tracing_test/test.py
Exception at line 5 --> 		raise ValueError('Invalid parameters !')
*  with variables {'x': True, 'y': 1, 'z': 6}
*  of /home/fred/Projects/tracing_test/test.py
